In [68]:
# Créez un dataframe contenant les informations de population de chaque pays. Calculez le nombre total d’humains sur la planète. 
# Critiquez votre résultat. En cas d’anomalie, analysez et effectuer les corrections nécessaires.

# Question 1 : donnez le résultat de votre calcul pour l'année 2013.
    
import pandas as pd
import numpy as np

data = pd.read_csv("P03/fr_population.csv", sep=",") #lire fichier csv

# Pop_sansagré =  data["Symbole"] != "A" #false si symbole = A
# Pop_total = data[Pop_sansagré] #masque = filtre des infos, enlève Agrégation
# np.sum(Pop_total["Valeur"]) #fait la somme de columns "valeur"

pop_mondial_2013 = np.sum(data[data["Symbole"] != "A"]["Valeur"])
pop_mondial_2013

6997326

In [69]:
import pandas as pd
import numpy as np


data_pop_withA = pd.read_csv("P03/fr_population.csv", sep=",")
filtre_Agrégation_pop = data_pop_withA["Symbole"] != "A"
data_pop = data_pop_withA[filtre_Agrégation_pop]

data_veg_withA = pd.read_csv("P03/fr_vegetaux.csv", sep=",")
filtre_Agrégation_veg = data_veg_withA["Symbole"] != "A"
data_veg = data_veg_withA[filtre_Agrégation_veg]

data_ani_withA = pd.read_csv("P03/fr_animaux.csv", sep=";", encoding="cp1252") #lis fichier encodé cp1252
filtre_Agrégation_ani = data_ani_withA["Symbole"] != "A"
data_ani = data_ani_withA[filtre_Agrégation_ani]



# Question 2 : Identifiez ces redondances, en donnant votre réponse sous forme de formule mathématique
# (pas besoin de coder ici :soleil: ). C'est une équation à 3 termes de type \(a_1 + a2 + [...] = b_1 + b_2 + [...] =
# c_1 + c_2 + [...]\) ) faisant intervenir chacune des 11 quantités données ci dessus. Illustrez cette équation avec 
# l'exemple du blé en France


print("Production + importation + variation de stock - exportation = Disponibilité intérieur = nourriture + semence + pertes + traitement + autre utilisation + aliment pour animaux")


# Question 3 : Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.

# 664 Dalim kcal et p
dalim_veg = (data_veg["Code Élément"] == 664) | (data_veg["Code Élément"] == 674) 
dalim_ani = (data_ani["Code Élément"] == 664) | (data_ani["Code Élément"] == 674) 
dalim = (data_veg[dalim_veg]).append(data_ani[dalim_ani]) #rajoute les lignes ani après veg

data_pop_filtrechine = (data_pop["Symbole"] == "A")
data_pop_clean = (data_pop[~data_pop_filtrechine])
pop = (data_pop_clean.drop(columns=["Code Domaine", "Domaine", "Code Élément", "Élément", "Code Produit", "Zone", "Code Produit", "Produit", "Code année", "Année", "Description du Symbole"]))
# suppression de colone avec doublon
dalim_pop = dalim.join(pop.set_index("Code zone"), lsuffix="_Dalim", rsuffix="_pop", on = "Code zone") # rajout info pop en colone



#afficher la valeur ainsi que l'unité calculé
dalim_pop["la disponibilité alimentaire"] =  np.where(dalim_pop['Code Élément']== 664, dalim_pop["Valeur_Dalim"] * (dalim_pop["Valeur_pop"] * 365 / 1000000), 
                                                (np.where(dalim_pop['Code Élément']== 674, dalim_pop["Valeur_Dalim"] * (dalim_pop["Valeur_pop"] * 365 / 1000000), dalim_pop["Valeur_Dalim"] * dalim_pop["Valeur_pop"] * 365 / 1000000)))

dalim_pop['unité'] = np.where(dalim_pop['Code Élément']== 664, "Milliards de Kcal", 
                                                (np.where(dalim_pop['Code Élément']== 674, "Millions de KiloGramme de Proteïne", "")))

print("\n la disponibilité alimentaire en kcal puis en kg de protéines pour chque produit et pays")
dalim_pop

Production + importation + variation de stock - exportation = Disponibilité intérieur = nourriture + semence + pertes + traitement + autre utilisation + aliment pour animaux

 la disponibilité alimentaire en kcal puis en kg de protéines pour chque produit et pays

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité_Dalim,Valeur_Dalim,Symbole_Dalim,Description du Symbole,Unité_pop,Valeur_pop,Symbole_pop,la disponibilité alimentaire,unité
8,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2511,Blé,2013,2013,Kcal/personne/jour,1369.00,Fc,Donnée calculée,1000 personnes,30552.0,NaN,15266.376120,Milliards de Kcal
9,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2511,Blé,2013,2013,g/personne/jour,36.91,Fc,Donnée calculée,1000 personnes,30552.0,NaN,411.601127,Millions de KiloGramme de Proteïne
18,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2805,Riz (Eq Blanchi),2013,2013,Kcal/personne/jour,141.00,Fc,Donnée calculée,1000 personnes,30552.0,NaN,1572.358680,Milliards de Kcal
19,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2805,Riz (Eq Blanchi),2013,2013,g/personne/jour,2.70,Fc,Donnée calculée,1000 personnes,30552.0,NaN,30.108996,Millions de KiloGramme de Proteïne
30,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2513,Orge,2013,2013,Kcal/personne/jour,26.00,Fc,Donnée calculée,1000 personnes,30552.0,NaN,289.938480,Milliards de Kcal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37147,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2766,Cephalopodes,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,1000 personnes,14150.0,NaN,0.000000,Millions de KiloGramme de Proteïne
37155,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2767,"Mollusques, Autres",2013,2013,Kcal/personne/jour,0.00,Fc,Donnée calculée,1000 personnes,14150.0,NaN,0.000000,Milliards de Kcal
37156,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2767,"Mollusques, Autres",2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,1000 personnes,14150.0,NaN,0.000000,Millions de KiloGramme de Proteïne
37163,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,2013,Kcal/personne/jour,0.00,Fc,Donnée calculée,1000 personnes,14150.0,NaN,0.000000,Milliards de Kcal
37164,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,1000 personnes,14150.0,NaN,0.000000,Millions de KiloGramme de Proteïne

In [70]:
# Question 4 : A partir de ces dernières informations, et à partir du poids de la disponibilité alimentaire
# (pour chaque pays et chaque produit), calculez pour chaque produit le ratio "énergie/poids", 
# que vous donnerez en kcal/kg.

# Masque pour sélectionner la nourriture 
masque_5142_veg = (data_veg["Code Élément"] == 5142)
masque_5142_ani = (data_ani["Code Élément"] == 5142)
data_alim_5142 = (data_veg[masque_5142_veg]).append(data_ani[masque_5142_ani]) #fusion de animaux plus vég

# nettoyage de colonne supplémentaire 
data_alim_5142_clean = (data_alim_5142.drop(columns=["Code Domaine", "Domaine", "Code Élément", "Élément", "Zone", "Produit", "Code année", "Année", "Description du Symbole"]))

#rajout de la colonne valeur correspondant à la nourriture en plus de la pop à Dalim
dalim_pop_5142 = pd.merge(dalim_pop, 
             data_alim_5142_clean,
             left_on=["Code Produit","Code zone"],
             right_on=["Code Produit","Code zone"],  how = 'outer')
 
# Calcul du ratio en Kcal/Kg et kg de Proteine/Kg en fonction de la ligne obtenue en multipliant Kcal/p/j par 365 et la population diviser par la nourriture     
dalim_pop_5142["ratio kg dispo"] =  np.where(dalim_pop_5142['Code Élément']== 664, ((dalim_pop_5142["Valeur_Dalim"] * dalim_pop_5142["Valeur_pop"] * 365 * 1000) / (dalim_pop_5142["Valeur"] * 1000000)) , 
                                                                                   ((dalim_pop_5142["Valeur_Dalim"] * dalim_pop_5142["Valeur_pop"] * 365) / (dalim_pop_5142["Valeur"] * 1000000)))



# display units corresponding at each calcul
dalim_pop_5142['unité ratio'] = np.where(dalim_pop_5142['Code Élément']== 664, "Ratio Kcal/Kg", 
                                                (np.where(dalim_pop_5142['Code Élément']== 674, "Ratio Kg de Proteïne/Kg", "")))

dalim_pop_5142_clean = dalim_pop_5142.rename(columns={"Valeur" : "Valeur_nour"}) # rename columns or ligne

print("dataframe du ratio kcal/kg et gramme de proteine /kg \n")
display(dalim_pop_5142_clean)

dataframe du ratio kcal/kg et gramme de proteine /kg

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,...,Unité_pop,Valeur_pop,Symbole_pop,la disponibilité alimentaire,unité,Unité,Valeur_nour,Symbole,ratio kg dispo,unité ratio
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664.0,Disponibilité alimentaire (Kcal/personne/jour),2511,Blé,2013.0,2013.0,...,1000 personnes,30552.0,NaN,15266.376120,Milliards de Kcal,Milliers de tonnes,4895.0,S,3118.769381,Ratio Kcal/Kg
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674.0,Disponibilité de protéines en quantité (g/pers...,2511,Blé,2013.0,2013.0,...,1000 personnes,30552.0,NaN,411.601127,Millions de KiloGramme de Proteïne,Milliers de tonnes,4895.0,S,0.084086,Ratio Kg de Proteïne/Kg
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664.0,Disponibilité alimentaire (Kcal/personne/jour),2805,Riz (Eq Blanchi),2013.0,2013.0,...,1000 personnes,30552.0,NaN,1572.358680,Milliards de Kcal,Milliers de tonnes,422.0,S,3725.968436,Ratio Kcal/Kg
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674.0,Disponibilité de protéines en quantité (g/pers...,2805,Riz (Eq Blanchi),2013.0,2013.0,...,1000 personnes,30552.0,NaN,30.108996,Millions de KiloGramme de Proteïne,Milliers de tonnes,422.0,S,0.071348,Ratio Kg de Proteïne/Kg
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664.0,Disponibilité alimentaire (Kcal/personne/jour),2513,Orge,2013.0,2013.0,...,1000 personnes,30552.0,NaN,289.938480,Milliards de Kcal,Milliers de tonnes,89.0,S,3257.735730,Ratio Kcal/Kg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25988,NaN,NaN,39,NaN,NaN,NaN,2612,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Milliers de tonnes,0.0,S,NaN,
25989,NaN,NaN,39,NaN,NaN,NaN,2613,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Milliers de tonnes,0.0,S,NaN,
25990,NaN,NaN,222,NaN,NaN,NaN,2534,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Milliers de tonnes,0.0,S,NaN,
25991,NaN,NaN,222,NaN,NaN,NaN,2616,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Milliers de tonnes,0.0,S,NaN,
25992,NaN,NaN,249,NaN,NaN,NaN,2657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Milliers de tonnes,0.0,S,NaN,

In [71]:
# Question 5 : Citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids.
# Étonnamment, il arrive que ce ratio soit différent en fonction du pays. Il faudra donc réaliser pour chaque
# aliment une moyenne sur les différents pays. Vous créerez donc une nouvelle table grâce à une agrégation. 
# Attention à bien retirer les valeurs égales à 0 afin de ne pas fausser le calcul de la moyenne.
# Citez 5 aliments parmi les 20 aliments les plus riches en protéines.


# masque pour éliminer les valeurs 0 et infini + sélection du rztion Kcal/Kg
clean_cal_nan0 = (dalim_pop_5142["ratio kg dispo"] == 0) | (dalim_pop_5142["ratio kg dispo"] == "inf") | (dalim_pop_5142["Valeur"] == 0) | (dalim_pop_5142["Code Élément"] == 674)
# dropnan
dalim_pop_5142_clean_cal = dalim_pop_5142[~clean_cal_nan0]

# mise en forme tableau du ratio kcal/kg en fonction des produits et des pays
ratio_pdt_cal = dalim_pop_5142_clean_cal.pivot_table('ratio kg dispo', index='Produit', columns='Zone')




# réaliser la moyenne des ligne
ratio_moy_cal = ratio_pdt_cal.mean(axis = 1)






# trie selon les valeur + display only 5 highter value
print("les 20 aliment les plus caloriques en moyenne")
display(ratio_moy_cal.sort_values(ascending = False).head(20))

les 20 aliment les plus caloriques en moyenne

F:\w10\Programme\Anaconda\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

Produit
Huiles de Foie de Poisso    9982.932500
Huile de Sésame             9433.744729
Huile de Son de Riz         9361.549883
Huiles de Poissons          9003.715504
Huile d'Arachide            8935.765811
Huile d'Olive               8931.223447
Huile de Germe de Maïs      8871.762566
Huil Plantes Oleif Autr     8848.222893
Huile de Palmistes          8789.540277
Huile Graines de Coton      8750.320136
Huile de Palme              8719.419872
Huile de Tournesol          8693.245772
Huile de Soja               8635.808245
Huile de Colza&Moutarde     8627.372452
Huile de Coco               8565.739255
Graisses Animales Crue      7583.862063
Beurre, Ghee                7331.424291
Palmistes                   6496.635000
Sésame                      5796.120413
Arachides Decortiquees      5702.900100
dtype: float64

In [72]:
# Question 5 : Citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids.
# Étonnamment, il arrive que ce ratio soit différent en fonction du pays. Il faudra donc réaliser pour chaque aliment une moyenne sur les différents pays. Vous créerez donc une nouvelle table grâce à une agrégation. Attention à bien retirer les valeurs égales à 0 afin de ne pas fausser le calcul de la moyenne.
# Citez 5 aliments parmi les 20 aliments les plus riches en protéines.


# masque pour éliminer les valeurs 0 et infini + sélection du ratio kg proteine/kgproduit
clean_nan0_p = (dalim_pop_5142["ratio kg dispo"] == 0) | (dalim_pop_5142["ratio kg dispo"] == "inf") | (dalim_pop_5142["Valeur"] == 0) | (dalim_pop_5142["Code Élément"] == 664)
# dropnan
dalim_pop_5142_clean_p= dalim_pop_5142[~clean_nan0_p]

# mise en forme tableau du ratio kcal/kg en fonction des produits et des pays
ratio_pdt_p = dalim_pop_5142_clean_p.pivot_table('ratio kg dispo', index='Produit', columns='Zone')





# réaliser la moyenne des ligne
ratio_moy_p = ratio_pdt_p.mean(axis = 1)





# trie selon les valeur + display only 5 highter value
print("les 20 aliment les plus proteique en moyenne")
print(ratio_moy_p.sort_values(ascending = False).head(20))


#

les 20 aliment les plus proteique en moyenne
Produit
Graines Colza/Moutarde      0.285365
Soja                        0.285331
Arachides Decortiquees      0.251466
Pois                        0.223244
Légumineuses Autres         0.219716
Haricots                    0.215452
Abats Comestible            0.175610
Sésame                      0.175040
Viande, Autre               0.174024
Plantes Oleiferes, Autre    0.170544
Aliments pour enfants       0.148832
Viande de Bovins            0.143780
Cephalopodes                0.139904
Viande d'Ovins/Caprins      0.135803
Viande de Volailles         0.126209
Piments                     0.121003
Poissons Pelagiques         0.119346
Graines de tournesol        0.111823
Poissons Marins, Autres     0.110133
Épices, Autres              0.107418
dtype: float64

In [73]:
# Question 6 : Calculez, pour les produits végétaux uniquement, la disponibilité intérieure mondiale exprimée en kcal

dalim_cal = dalim_pop_5142_clean_cal.rename({'Valeur':"Valeur_nour", 'Unité':"Unité_nour", 'unité':"unité_Dalim_total", 'Unité_Dalim':"Unité_Dalim_parperson"}, axis='columns') # rename columns or ligne





DVDint = (data_veg["Code Élément"] == 5301)

data_veg_Dint= data_veg[DVDint]
data_veg_Dint_clean1= data_veg_Dint.drop(columns=["Code Domaine", "Domaine", "Code Élément", "Élément", "Zone", "Symbole", "Produit", "Code année", "Année", "Description du Symbole"])
data_veg_Dint_clean2= data_veg_Dint_clean1.rename({'Valeur':"Valeur_Dint", 'Unité':"Unité_Dint"}, axis='columns')

# rajouté calonne dispo alimentaire par produit par pays (en millier de Kg)
dalim_cal_Dint= pd.merge(dalim_cal, data_veg_Dint_clean2, left_on=["Code Produit","Code zone"], right_on=["Code Produit","Code zone"])
dalim_cal_Dint["Valeur_Dint_kcal"] = (dalim_cal_Dint["ratio kg dispo"] * dalim_cal_Dint["Valeur_Dint"] * 1000000)

print("La disponibilité intérieur mondial des végétaux en Kcal est : ")
print(np.sum(dalim_cal_Dint["Valeur_Dint_kcal"])) #somme colone
print("la réponse à la Q7 en personne pour les Kcal est : ")
pop_Dint_veg_kcal = (np.sum(dalim_cal_Dint["Valeur_Dint_kcal"]))/(2500*365) #2500 kcal moyen par persone par jour
print(pop_Dint_veg_kcal)
print("ce qui correspont en Kcal en % de la population mondiale actuel ")
print(pop_Dint_veg_kcal/((np.sum(data[data["Symbole"] != "A"]["Valeur"])*10))) #*1000 pour la pop et / par 100 pour les %


dalim_p = dalim_pop_5142_clean_p.rename({'Valeur':"Valeur_nour", 'Unité':"Unité_nour", 'unité':"unité_Dalim_total", 'Unité_Dalim':"Unité_Dalim_parperson"}, axis='columns') # rename columns or ligne
dalim_p_Dint=pd.merge(dalim_p, data_veg_Dint_clean2, left_on=["Code Produit","Code zone"], right_on=["Code Produit","Code zone"])
dalim_p_Dint["Valeur_Dint_p"] = (dalim_p_Dint["ratio kg dispo"] * dalim_p_Dint["Valeur_Dint"] * 1000000)

print("La disponibilité intérieur mondial des végétaux en proteine est : ")
print(np.sum(dalim_p_Dint["Valeur_Dint_p"])) #somme colone
print("la réponse à la Q7 en personne pour les proteine est : ")
pop_Dint_veg_p = ((np.sum(dalim_p_Dint["Valeur_Dint_p"]*1000))/(52*365)) #52g de proteine moyen par persone par jour pour 65kg et 0.8g de p / kg, * 1000 pour kg en g
print(pop_Dint_veg_p)
print("ce qui correspont en proteine en % de la population mondiale actuel ")
print((pop_Dint_veg_p)/((np.sum(data[data["Symbole"] != "A"]["Valeur"])*10))) #*1000 pour la pop et / par 100 pour les %

La disponibilité intérieur mondial des végétaux en Kcal est :
1.2312091265143276e+16
la réponse à la Q7 en personne pour les Kcal est :
13492702756.321398
ce qui correspont en Kcal en % de la population mondiale actuel
192.82655626336972
La disponibilité intérieur mondial des végétaux en proteine est :
290177334142.13525
la réponse à la Q7 en personne pour les proteine est :
15288584517.49922
ce qui correspont en proteine en % de la population mondiale actuel
218.49181412298384

In [74]:
# Question 8 : Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux la 
# nourriture végétale destinée aux animaux et les pertes de produits végétaux étaient utilisés pour de la nourriture ? Donnez 
# les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population 
# mondiale.

DVAlimani= (data_veg["Code Élément"] == 5521)  # Aliment pour animaux 
data_veg_alimentani = data_veg[DVAlimani]
data_veg_alimentani_clean = data_veg_alimentani.drop(columns=["Code Domaine", "Domaine", "Code Élément", "Élément", "Zone", "Symbole", "Produit", "Code année", "Année", "Description du Symbole"])
data_veg_alimentani_clean2 = data_veg_alimentani_clean.rename({'Valeur':"Valeur_Alim_ani", 'Unité':"Unité_Alim_ani"}, axis='columns')


dalim_cal_alimentani = pd.merge(dalim_cal, data_veg_alimentani_clean2, left_on=["Code Produit","Code zone"], right_on=["Code Produit","Code zone"])
dalim_cal_alimentani["Valeur_alimentani_kcal"] = (dalim_cal_alimentani["ratio kg dispo"] * dalim_cal_alimentani["Valeur_Alim_ani"] * 1000000)


print("les végétaux attribué à la nourriture pour animaux pourrait nourrir un nombre d'humain en kcal de :")
pop_kcal_aliani = np.sum(dalim_cal_alimentani["Valeur_alimentani_kcal"])/(2500*365)
print(pop_kcal_aliani)
print("ce qui correspont en Kcal en % de la population mondiale actuel :")
print((pop_kcal_aliani)/((np.sum(data[data["Symbole"] != "A"]["Valeur"])*10))) #*1000 pour la pop et / par 100 pour les %

dalim_p_alimentani = pd.merge(dalim_p, data_veg_alimentani_clean2, left_on=["Code Produit","Code zone"], right_on=["Code Produit","Code zone"])
dalim_p_alimentani["Valeur_alimentani_p"] = (dalim_p_alimentani["ratio kg dispo"] * dalim_p_alimentani["Valeur_Alim_ani"] * 1000000)



print("les végétaux attribué à la nourriture pour animaux pourrait nourrir un nombre d'humain en proteine de :")
pop_p_aliani = (np.sum(dalim_p_alimentani["Valeur_alimentani_p"])*1000)/(52*365) #*1000 pour passer des kg en g
print(pop_p_aliani)
print("ce qui correspont en proteine en % de la population mondiale actuel ")
print((pop_p_aliani)/((np.sum(data[data["Symbole"] != "A"]["Valeur"])*10))) #*1000 pour la pop et / par 100 pour les %

les végétaux attribué à la nourriture pour animaux pourrait nourrir un nombre d'humain en kcal de :
2864114254.0946465
ce qui correspont en Kcal en % de la population mondiale actuel :
40.93155376917763
les végétaux attribué à la nourriture pour animaux pourrait nourrir un nombre d'humain en proteine de :
3470996127.9024324
ce qui correspont en proteine en % de la population mondiale actuel
49.60460793026411

In [85]:
# Question 9 : Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale ? Donnez les résultats 
# en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.


print("avec la Disponibilité alimentaire actuel nous pouvont nourrir un nombre de personnes de : ")
pop_max_Dalim_cal = (np.sum(dalim_cal["la disponibilité alimentaire"])*1000000000)/(2500*365)
print(pop_max_Dalim_cal)

print("ce qui correspont en kcal en % de la population mondiale actuel ")
print((pop_max_Dalim_cal)/((np.sum(data[data["Symbole"] != "A"])["Valeur"])*10)) #*1000 pour la pop et / par 100 pour les %

avec la Disponibilité alimentaire actuel nous pouvont nourrir un nombre de personnes de :
8069054021.6
ce qui correspont en kcal en % de la population mondiale actuel
115.31625111649794

In [27]:
# Question 10 : A partir des données téléchargées qui concernent la sous-nutrition, répondez à cette question : 
# Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?

data_sousnutri = pd.read_csv("P03/fr_sousalimentation.csv", sep=";", encoding="ANSI", decimal=".")
# filtre pour les valeur 2013 en delete nan and <0.1
data_sousnutri_0nan = (data_sousnutri["Valeur"] == "0") | (data_sousnutri["Valeur"] == "<0.1") | (data_sousnutri["Code année"] != 20122014) | (data_sousnutri["Symbole"] == "NR")  | (data_sousnutri["Symbole"] == "NV") 
data_sousnutri_clean = data_sousnutri[~data_sousnutri_0nan]

# prendre les données sous forme de liste
person_sousalim = data_sousnutri_clean["Valeur"]

# conversion liste objet en float
nbperson_sousalim = np.sum([float(i) for i in person_sousalim])

print("En moyenne sur 3 ans (2012-2014) le nombre de personnes sous alimenté en millions est de:")
print(nbperson_sousalim)
print("ce qui correspont en % de la population mondiale actuel a : ")
print((nbperson_sousalim*1000000)/((np.sum(data[data["Symbole"] != "A"]["Valeur"])*10))) #*1000 pour la pop et / par 100 pour les %

En moyenne sur 3 ans (2012-2014) le nombre de personnes sous alimenté en millions est de:
881.4
ce qui correspont en % de la population mondiale actuel a :
12.596240335236631

In [28]:
# Établissez la liste des produits (ainsi que leur code) considéré comme des céréales selon la FAO.
data_cer = pd.read_csv("P03/fr_céréales.csv", sep=";", encoding="ANSI", decimal=".")

data_cer_list = (data_cer.loc[:, data_cer.columns.intersection(['Produit','Code Produit'])])
cer_list = data_cer_list.drop_duplicates()




# Repérez dans vos données les informations concernant les céréales (par exemple en créant une colonne de 
# type booléen nommée "is_cereal").

cer_list["is_cereal"] = True


# Question 11 : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale),
# quelle proportion (en termes de poids) est destinée à l'alimentation animale ?

data_veg2 = pd.read_csv("P03/fr_vegetaux.csv", sep=",")



veg_cer = pd.merge(data_veg2, 
             cer_list,
             left_on=["Code Produit","Produit"],
             right_on=["Code Produit","Produit"])





# faire la somme des nourriture
veg_alimani_nour_filtre = (veg_cer["Code Élément"] == 5521)  | (veg_cer["Code Élément"] == 5142) 
veg_alimani_nour = veg_cer[veg_alimani_nour_filtre]
sommealimentanietnour = np.sum(veg_alimani_nour["Valeur"])

# calculé les céréales destiné aux animaux
veg_alimani_nour_alimani_filtre = (veg_alimani_nour["Code Élément"] == 5521)
veg_alimani_nour_alimani = veg_alimani_nour[veg_alimani_nour_alimani_filtre]
sommealimentani = np.sum(veg_alimani_nour_alimani["Valeur"])

print("en proportion des céréales destiné à l'alimentation (humaine ou animal) l'alimentation animal représente en kg en % :")
print(sommealimentani/sommealimentanietnour)




# Sélectionnez parmi les données des bilans alimentaires les informations relatives aux pays dans lesquels la FAO 
# recense des personnes en sous-nutrition.

data_veg_ani = (data_veg).append(data_ani) #rajoute les lignes ani après veg

data_sousnutri_pays2013_filtre = (data_sousnutri["Code année"] != 20122014) | (data_sousnutri["Valeur"] == "0") | (data_sousnutri["Symbole"] == "NR")  | (data_sousnutri["Symbole"] == "NV")
data_sousnutri_pays2013 = data_sousnutri[~data_sousnutri_pays2013_filtre]
data_sousnutri_pays2013_clean = (data_sousnutri_pays2013.loc[:, data_sousnutri_pays2013.columns.intersection(['Code zone','Valeur', 'Unité'])])
data_sousnutri_pays2013_clean2 = data_sousnutri_pays2013_clean.rename(columns={"Valeur": "sous_alimenté", "Unité": "Unité_sous_alimenté"})




veg_ani_faim = pd.merge(data_veg_ani, 
             data_sousnutri_pays2013_clean2,
             left_on=["Code zone"],
             right_on=["Code zone"])



# Repérez les 15 produits les plus exportés par ce groupe de pays.

veg_ani_faim_export_filtre = (veg_ani_faim["Code Élément"] == 5911)
veg_ani_faim_export = veg_ani_faim[veg_ani_faim_export_filtre]


veg_ani_faim_export_parpdt = veg_ani_faim_export.pivot_table('Valeur', index='Produit', columns='Année')


veg_ani_faim_export_parpdt_max = veg_ani_faim_export_parpdt.sort_values(by=[2013], ascending  = False)
veg_ani_faim_export_parpdt_max1 = veg_ani_faim_export_parpdt_max.iloc[0:15,[0]]
print("les 15 produit les plus exporter (en kg) par les pays sous aliméneté sont les suivant")
display(veg_ani_faim_export_parpdt_max1)

# Parmi les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations 
# de ces produits (1 importation = une quantité d'un produit donné importée par un pays donné)

<ipython-input-28-48db1a1394a4>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cer_list["is_cereal"] = True

en proportion des céréales destiné à l'alimentation (humaine ou animal) l'alimentation animal représente en kg en % :
0.4630652303481541
les 15 produit les plus exporter (en kg) par les pays sous aliméneté sont les suivant

Année                      2013
Produit
Huile de Palme       467.919192
Manioc               448.137500
Maïs                 375.306931
Riz (Eq Blanchi)     306.416667
Sucre Eq Brut        237.254545
Blé                  222.298246
Bananes              191.361702
Soja                 177.666667
Légumes, Autres      173.612069
Lait - Excl Beurre   138.638889
Poissons Pelagiques  128.918182
Fruits, Autres       128.859649
Tomates               86.747573
Pommes                83.126316
Orge                  76.593023

In [41]:
# les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations 
# de ces produits (1 importation = une quantité d'un produit donné importée par un pays donné)




veg_ani_faim_export_merge = pd.merge(data_veg_ani, 
             veg_ani_faim_export_parpdt_max1,
             left_on = [ "Produit"],
             right_on = [ "Produit"])

# masque importation
veg_ani_faim_import_export_merge_filtre = (veg_ani_faim_export_merge["Code Élément"] == 5611)  
veg_ani_faim_import_export_merge = veg_ani_faim_export_merge[veg_ani_faim_import_export_merge_filtre]


# trie par valeur d'importation
veg_ani_faim_import_export_merge_max = veg_ani_faim_import_export_merge.sort_values(by=["Valeur"], ascending  = False)

veg_ani_faim_import_export_merge_max_nochinefiltre =  (veg_ani_faim_import_export_merge_max["Symbole"] == "A") 

veg_ani_faim_import_export_merge_max_nochine = veg_ani_faim_import_export_merge_max[~veg_ani_faim_import_export_merge_max_nochinefiltre]
veg_ani_faim_import_export_max = veg_ani_faim_import_export_merge_max_nochine.iloc[0:200]

# print("importation des 15 pdt les plus exporter par les pays en SN")
# display(veg_ani_faim_import_export_max)



# Groupez ces importations par produit, afin d'avoir une table contenant 1 ligne pour chacun des 15 produits.
print("importation par produit avec les 15 produits les plus exportés par les pays en sous nutrition pour les 200 plus grandes importation de ces produits")

sum_export_pdt_SN = veg_ani_faim_import_export_max.pivot_table('Valeur', index={ "Code Produit", "Produit"}, columns= "Année")

display(sum_export_pdt_SN)

# Ensuite, calculez pour chaque produit les 2 quantités suivantes :
# le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure.

#filtre other use
data_veg_ani_Other_filtre = (data_veg_ani["Code Élément"] == 5154) 
data_veg_ani_Other = data_veg_ani[data_veg_ani_Other_filtre]
data_veg_ani_Other_clean = (data_veg_ani_Other.loc[:, data_cer.columns.intersection(["Zone", 'Produit','Code Produit', "Valeur", 'Code zone'])])

#filtre Dalim intérieur
data_veg_ani_DAint_filtre = (data_veg_ani["Code Élément"] == 5301) 
data_veg_ani_DAint = data_veg_ani[data_veg_ani_DAint_filtre]
data_veg_ani_DAint_clean = (data_veg_ani_DAint.loc[:, data_cer.columns.intersection(["Zone", 'Produit','Code Produit', "Valeur", 'Code zone'])])

#merge avec Veg_ani_faim_import_export_max qui correspont au 200 importation




veg_ani_Other = pd.merge(data_veg_ani_Other_clean,
                         veg_ani_faim_import_export_merge,              
             left_on=["Code Produit", "Produit", "Code zone", "Zone"],
             right_on=["Code Produit", "Produit", "Code zone", "Zone"])

veg_ani_Other_clean = veg_ani_Other.rename(columns={"Valeur_x": "Other_use", "Valeur_y": "Importation"})

veg_ani_Other_DAint  = pd.merge(data_veg_ani_DAint_clean,
                         veg_ani_Other_clean,              
             left_on=["Code Produit", "Produit", "Code zone", "Zone"],
             right_on=["Code Produit", "Produit", "Code zone", "Zone"])

veg_ani_Other_DAint_clean = veg_ani_Other_DAint.rename(columns={"Valeur": "DAint"})

veg_ani_Other_DAint_clean["Ratio_other_DAint"] = (veg_ani_Other_DAint_clean["Other_use"] / veg_ani_Other_DAint_clean["DAint"])

table_ratio_Otheruse_DAint = veg_ani_Other_DAint_clean.pivot_table('Ratio_other_DAint', index={ "Code Produit", "Produit"}, columns= "Année")

table_ratio_Otheruse_DAint_tri =  table_ratio_Otheruse_DAint.sort_values(by = [2013] ,  ascending=False)

print("Q12 : les 3 produit ayant le ratio otheruse/DAint le plus élevé sont : ")
display(table_ratio_Otheruse_DAint_tri.iloc[0:3,[0]])

# le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

#filtre nourriture
veg_ani_nour = data_veg_ani[(data_veg_ani["Code Élément"] == 5142) ]
veg_ani_nour_clean = (veg_ani_nour.loc[:, veg_ani_nour.columns.intersection(["Zone", 'Produit','Code Produit', "Valeur", 'Code zone'])])


# filtre aliment pour animaux
veg_ani_alimA = data_veg_ani[(data_veg_ani["Code Élément"] == 5521) ]
veg_ani_alimA_clean = (veg_ani_alimA.loc[:, veg_ani_alimA.columns.intersection(["Zone", 'Produit','Code Produit', "Valeur", 'Code zone'])])

# merge ac les 200 importation

veg_ani_nour = pd.merge(veg_ani_nour_clean,
                         veg_ani_faim_import_export_merge,              
             left_on=["Code Produit", "Produit", "Code zone", "Zone"],
             right_on=["Code Produit", "Produit", "Code zone", "Zone"])
veg_ani_nour_clean = veg_ani_nour.rename(columns={"Valeur_x": "Nourriture", "Valeur_y": "Importation"})

veg_ani_nour_alimA  = pd.merge(veg_ani_alimA_clean,
                         veg_ani_nour_clean,              
             left_on=["Code Produit", "Produit", "Code zone", "Zone"],
             right_on=["Code Produit", "Produit", "Code zone", "Zone"])

veg_ani_nour_alimA_clean = veg_ani_nour_alimA.rename(columns={"Valeur": "alimA"})

veg_ani_nour_alimA_clean["Ratio_AlimA_Nourtotal"] = (veg_ani_nour_alimA_clean["alimA"]) / ( (veg_ani_nour_alimA_clean["alimA"]) + (veg_ani_nour_alimA_clean["Nourriture"]))

table_ratio_alimA_nourTotal = veg_ani_nour_alimA_clean.pivot_table('Ratio_AlimA_Nourtotal', index={ "Code Produit", "Produit"}, columns= "Année")

table_ratio_alimA_nourTotal_tri = table_ratio_alimA_nourTotal.sort_values(by = [2013] ,  ascending=False)

print("Q12 : les 3 produit ayant le ratio Nourriture animal/nourriture total (h+a) le plus élevé sont : ")
display(table_ratio_alimA_nourTotal_tri.iloc[0:3,[0]])


veg_ani_Other_DAint_clean.drop(columns = ["Code Domaine", "Domaine", "Code Élément", "Élément", "Code année", "Importation", "Année", 2013, "Symbole", "Description du Symbole"]).head(15)

importation par produit avec les 15 produits les plus exportés par les pays en sous nutrition pour les 200 plus grandes importation de ces produits

Année                                    2013
Produit             Code Produit
Bananes             2615          1932.600000
Blé                 2511          3432.000000
Fruits, Autres      2625          2244.857143
Huile de Palme      2577          2974.700000
Lait - Excl Beurre  2848          3194.642857
Légumes, Autres     2605          2561.545455
Manioc              2532          6931.000000
Maïs                2514          3658.964286
Orge                2513          3198.142857
Poissons Pelagiques 2763          2240.833333
Pommes              2617          1703.600000
Riz (Eq Blanchi)    2805          1554.444444
Soja                2555          6230.333333
Sucre Eq Brut       2542          2138.000000
Tomates             2601          1428.600000

Q12 : les 3 produit ayant le ratio otheruse/DAint le plus élevé sont :

Année                            2013
Produit        Code Produit
Huile de Palme 2577          0.651857
Manioc         2532          0.320163
Sucre Eq Brut  2542          0.142068

Q12 : les 3 produit ayant le ratio Nourriture animal/nourriture total (h+a) le plus élevé sont :

Année                     2013
Produit Code Produit
Orge    2513          0.777862
Soja    2555          0.763815
Maïs    2514          0.646357

,Code zone,Zone,Code Produit,Produit,DAint,Other_use,Unité,Ratio_other_DAint
0,2,Afghanistan,2577,Huile de Palme,119.0,55.0,Milliers de tonnes,0.462185
1,202,Afrique du Sud,2514,Maïs,10480.0,0.0,Milliers de tonnes,0.000000
2,202,Afrique du Sud,2532,Manioc,57.0,57.0,Milliers de tonnes,1.000000
3,202,Afrique du Sud,2577,Huile de Palme,449.0,399.0,Milliers de tonnes,0.888641
4,3,Albanie,2511,Blé,650.0,130.0,Milliers de tonnes,0.200000
5,3,Albanie,2805,Riz (Eq Blanchi),25.0,0.0,Milliers de tonnes,0.000000
6,3,Albanie,2513,Orge,19.0,1.0,Milliers de tonnes,0.052632
7,3,Albanie,2514,Maïs,420.0,3.0,Milliers de tonnes,0.007143
8,3,Albanie,2532,Manioc,0.0,0.0,Milliers de tonnes,NaN
9,3,Albanie,2542,Sucre Eq Brut,69.0,13.0,Milliers de tonnes,0.188406
10,3,Albanie,2577,Huile de Palme,2.0,2.0,Milliers de tonnes,1.000000
11,4,Algérie,2511,Blé,9461.0,820.0,Milliers de tonnes,0.086672
12,4,Algérie,2542,Sucre Eq Brut,1279.0,190.0,Milliers de tonnes,0.148554
13,4,Algérie,2577,Huile de Palme,82.0,52.0,Milliers de tonnes,0.634146
14,79,Allemagne,2511,Blé,16491.0,774.0,Milliers de tonnes,0.046935

In [17]:
# Question 13 : Combien de tonnes de céréales pourraient être libérées si les USA diminuaient leur production 
# de produits animaux de 10% ?
veg_USA_filtre = data_veg2["Code zone"] == 231
veg_USA = data_veg2[veg_USA_filtre]
cer_USA = veg_USA[veg_USA["Produit"].isin(cer_list["Produit"])]


cer_USA_alimA_filtre = cer_USA["Code Élément"] == 5521
cer_USA_alimA = cer_USA[cer_USA_alimA_filtre]
cer_USA_alimA_sum10 = np.sum(cer_USA_alimA["Valeur"])*0.1
display("si les USA diminuer de 10% la nourriture attribuer aux animaux cela ferait économiser en millier de tonne de céréale :")
display(cer_USA_alimA_sum10)

'si les USA diminuer de 10% la nourriture attribuer aux animaux cela ferait économiser en millier de tonne de céréale :'

14009.6

In [18]:
# Question 14 : En Thaïlande, quelle proportion de manioc est exportée ? 
veg_Thai_filtre = (data_veg2["Code zone"] == 216)
veg_Thai= data_veg2[veg_Thai_filtre]

veg_Thai_manioc_filtre = veg_Thai["Code Produit"] == 2532
veg_Thai_manioc = veg_Thai[veg_Thai_manioc_filtre]

veg_Thai_manioc_prod = veg_Thai_manioc[veg_Thai_manioc["Code Élément"] == 5511]
Prod_manioc_Thai = np.sum(veg_Thai_manioc_prod["Valeur"])

veg_Thai_manioc_export = veg_Thai_manioc[veg_Thai_manioc["Code Élément"] == 5911]
Export_manioc_Thai =  np.sum(veg_Thai_manioc_export["Valeur"])

pourcent_manioc_exporter = (Export_manioc_Thai/Prod_manioc_Thai)

display("la proportion de manioc exporté par rapport à la production de manioc de la thailande est de : ")
display(pourcent_manioc_exporter)

# Quelle est la proportion de personnes en sous-nutrition?

data_sousnutri_Thai = data_sousnutri[data_sousnutri["Code zone"] == 216]
data_sousnutri_Thai_2013 = data_sousnutri_Thai[data_sousnutri_Thai["Code année"] == 20122014]
personesousalimentétahailande2013 = np.sum(data_sousnutri_Thai_2013["Valeur"]) # en millions

data_pop_Thai = data_pop[data_pop["Code zone"] == 216]
poptotalthai2013 = np.sum(data_pop_Thai["Valeur"])/1000

print("la proportion de persone sous alimenté en thailande en % est de : ")
print(float(personesousalimentétahailande2013) / float(poptotalthai2013) )

'la proportion de manioc exporté par rapport à la production de manioc de la thailande est de : '

0.8341272991928014

la proportion de persone sous alimenté en thailande en % est de :
0.08356836937219263

In [45]:
# Q19, code python pour créer les tables SQL demandé


p3_pop_filtre = ["Code zone", "Zone", "Année", "Valeur"] #filtre colone
data_pop_clean = data_pop[p3_pop_filtre]
data_pop_clean["population"]= data_pop_clean["Valeur"]*1000
p3_bdd_pop = data_pop_clean.drop(columns=["Valeur"])


p3_bdd_pop.to_csv(path_or_buf="P03/fr_bdd_pop.csv", sep=';') # crée fichier CSV avec Dataframe



p3_pop_merge_filtre = ["Code zone", "population"] #filtre colone pou préparer merge
p3_pop_merge = p3_bdd_pop[p3_pop_merge_filtre]


data_veg["origin"]="Végétales" #rajoute colon orgine (animal/végétal)
data_ani["origin"]="Animal"
p3_veg_ani = data_veg.append(data_ani) # rajoute animaux au végétaux


p3_veg_ani_clean = p3_veg_ani.drop(columns=["Domaine", "Code année","Code Domaine", "Symbole", "Description du Symbole"])

p3_veg_ani_pop = pd.merge(p3_pop_merge, #rajoute valeur pop pour calcul dalimtotal
                         p3_veg_ani_clean,              
             left_on=[ "Code zone"],
             right_on=["Code zone"])

# rajout collone dispo_alim_tonnes
p3_veg_ani_pop_Dalmitotal = p3_veg_ani_pop[p3_veg_ani_pop["Code Élément"] == 645]
p3_veg_ani_pop_Dalmitotal["dispo_alim_tonnes"] = (p3_veg_ani_pop_Dalmitotal["population"]*p3_veg_ani_pop_Dalmitotal["Valeur"]/1000)
p3_veg_ani_pop_Dalmitotal_clean = p3_veg_ani_pop_Dalmitotal.drop(columns=["population", "Valeur", "Code Élément", "Élément", "Unité"])


p3_veg_ani_pop_Dalmitotal_kcal = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 664], #rajoute valeur kcal
                         p3_veg_ani_pop_Dalmitotal_clean,  how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_pop_Dalmitotal_kcal_clean = p3_veg_ani_pop_Dalmitotal_kcal.rename(columns={"Valeur": "dispo_alim_kcal_p_j"})
p3_veg_ani_pop_Dalmitotal_kcal_clean2 = p3_veg_ani_pop_Dalmitotal_kcal_clean.drop(columns=["Code Élément", "Élément", "Unité"])




p3_veg_ani_pop_Dalmitotal_kcal_p = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 674], #rajoute valeur p
                         p3_veg_ani_pop_Dalmitotal_kcal_clean2,  how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_pop_Dalmitotal_kcal_p_clean = p3_veg_ani_pop_Dalmitotal_kcal_p.rename(columns={"Valeur": "dispo_prot"})
p3_veg_ani_pop_Dalmitotal_kcal_p_clean2 = p3_veg_ani_pop_Dalmitotal_kcal_p_clean.drop(columns=["Code Élément", "Élément", "Unité"])


p3_veg_ani_pop_Dalmitotal_kcal_p_mg = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 684], #rajoute valeur mg
                         p3_veg_ani_pop_Dalmitotal_kcal_p_clean2,  how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_pop_Dalmitotal_kcal_p_mg_clean = p3_veg_ani_pop_Dalmitotal_kcal_p_mg.rename(columns={"Valeur": "dispo_mat_gr"})
p3_veg_ani_pop_Dalmitotal_kcal_p_mg_clean2 = p3_veg_ani_pop_Dalmitotal_kcal_p_mg_clean.drop(columns=["Code Élément", "Élément", "Unité"])

p3_bdd_dispo_alim = p3_veg_ani_pop_Dalmitotal_kcal_p_mg_clean2.fillna(-999)
p3_bdd_dispo_alim.to_csv(path_or_buf="P03/fr_bdd_dispo_alim.csv", sep=';') # crée fichier CSV avec Dataframe




# Merge en série pour rajouter les colonnes
p3_veg_ani_Dalimint = ((p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5301]).rename(columns={"Valeur": "Dalimint"})
                      ).drop(columns=["Code Élément", "Élément", "Unité"])


p3_veg_ani_Dalimint_sem = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5527], #rajoute valeur semence
                         p3_veg_ani_Dalimint,  how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_Dalimint_sem_clean = (p3_veg_ani_Dalimint_sem.rename(columns={"Valeur": "semences"})).drop(columns=["Code Élément", "Élément", "Unité"])


p3_veg_ani_Dalimint_sem_perte = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5123], #rajoute valeur perte
                         p3_veg_ani_Dalimint_sem_clean,   how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_Dalimint_sem_perte_clean = (p3_veg_ani_Dalimint_sem_perte.rename(columns={"Valeur": "pertes"})).drop(columns=["Code Élément", "Élément", "Unité"])


p3_veg_ani_Dalimint_sem_perte_nour = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5142], #rajoute valeur nourriture
                         p3_veg_ani_Dalimint_sem_perte_clean,   how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_Dalimint_sem_perte_nour_clean = (p3_veg_ani_Dalimint_sem_perte_nour.rename(columns={"Valeur": "nourriture "})).drop(columns=["Code Élément", "Élément", "Unité"])


p3_veg_ani_Dalimint_sem_perte_nour_alima = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5521], #rajoute valeur alim animaux
                         p3_veg_ani_Dalimint_sem_perte_nour_clean,   how = 'outer',             
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_Dalimint_sem_perte_nour_alima_clean = (p3_veg_ani_Dalimint_sem_perte_nour_alima.rename(columns={"Valeur": "alim_ani "})).drop(columns=["Code Élément", "Élément", "Unité"])


p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5154], #rajoute valeur autres_utilisations
                         p3_veg_ani_Dalimint_sem_perte_nour_alima_clean,  how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse_clean = (p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse.rename(columns={"Valeur": "autres_utilisations "})).drop(columns=["Code Élément", "Élément", "Unité"])


p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse_trait = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5131], #rajoute valeur traitement
                         p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse_clean,  how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])
p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse_trait_clean = (p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse_trait.rename(columns={"Valeur": "traitement "})).drop(columns=["Code Élément", "Élément", "Unité", "origin"])

p3_bdd_equilibre_prod = p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse_trait_clean.fillna(-999)
p3_bdd_equilibre_prod.to_csv(path_or_buf="P03/fr_bdd_equilibre_prod.csv", sep=';') # crée fichier CSV avec Dataframe
p3_bdd_equilibre_prod
p3_bdd_dispo_alim.head(20)

<ipython-input-45-55d9d4b0a130>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_pop_clean["population"]= data_pop_clean["Valeur"]*1000
<ipython-input-45-55d9d4b0a130>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_veg["origin"]="Végétales" #rajoute colon orgine (animal/végétal)
<ipython-input-45-55d9d4b0a130>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_ani["origin"]="Animal"
<ipython-input-45-55d9d4b0a130>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p3_veg_ani_pop_Dalmitotal["dispo_alim_tonnes"] = (p3_veg_ani_pop_Dalmitotal["population"]*p3_veg_ani_pop_Dalmitotal["Valeur"]/1000)

,Code zone,Zone,Code Produit,Produit,Année,dispo_mat_gr,origin,dispo_prot,dispo_alim_kcal_p_j,dispo_alim_tonnes
0,2,Afghanistan,2511,Blé,2013,4.69,Végétales,36.91,1369.0,4895346.96
1,2,Afghanistan,2805,Riz (Eq Blanchi),2013,0.27,Végétales,2.70,141.0,422228.64
2,2,Afghanistan,2513,Orge,2013,0.24,Végétales,0.79,26.0,89211.84
3,2,Afghanistan,2514,Maïs,2013,0.30,Végétales,0.56,21.0,76380.00
4,2,Afghanistan,2517,Millet,2013,0.02,Végétales,0.08,3.0,12220.80
5,2,Afghanistan,2520,"Céréales, Autres",2013,0.00,Végétales,0.00,0.0,0.00
6,2,Afghanistan,2531,Pommes de Terre,2013,0.04,Végétales,0.25,15.0,230056.56
7,2,Afghanistan,2549,Légumineuses Autres,2013,0.14,Végétales,1.56,23.0,74546.88
8,2,Afghanistan,2551,Noix,2013,1.07,Végétales,0.38,12.0,44300.40
9,2,Afghanistan,2560,Coco (Incl Coprah),2013,0.00,Végétales,0.00,0.0,0.00
10,2,Afghanistan,2561,Sésame,2013,0.77,Végétales,0.27,9.0,15887.04
11,2,Afghanistan,2563,Olives,2013,0.03,Végétales,0.00,0.0,1833.12
12,2,Afghanistan,2571,Huile de Soja,2013,1.46,Végétales,-999.00,13.0,16192.56
13,2,Afghanistan,2572,Huile d'Arachide,2013,0.00,Végétales,-999.00,0.0,0.00
14,2,Afghanistan,2573,Huile de Tournesol,2013,2.06,Végétales,-999.00,18.0,22914.00
15,2,Afghanistan,2574,Huile de Colza&Moutarde,2013,0.18,Végétales,-999.00,2.0,2138.64
16,2,Afghanistan,2575,Huile Graines de Coton,2013,0.34,Végétales,-999.00,3.0,3666.24
17,2,Afghanistan,2577,Huile de Palme,2013,5.74,Végétales,-999.00,51.0,63853.68
18,2,Afghanistan,2579,Huile de Sésame,2013,0.13,Végétales,-999.00,1.0,1527.60
19,2,Afghanistan,2580,Huile d'Olive,2013,0.05,Végétales,-999.00,0.0,611.04

In [20]:
p3_sousnutri = data_sousnutri.drop(columns=["Code Élément", "Élément", "Unité", "Domaine", "Année","Code Domaine", "Produit", "Note", "Symbole", "Description du Symbole"])

p3_sousnutri_2013 = p3_sousnutri[p3_sousnutri["Code année"] == 20122014]

# p3_sousnutri_2013["nb_personnes"] = float(p3_sousnutri_2013["Valeur"])





# converti valeur en float
p3_sousnutri_2013["nb_personnes"] = pd.to_numeric(p3_sousnutri_2013["Valeur"], errors='coerce')*1000000
p3_sousnutri_2013["Année"] = 2013

p3_bdd_sous_nutrition = p3_sousnutri_2013.drop(columns=["Code Produit", "Code année", "Valeur"]).fillna(-999)




p3_bdd_sous_nutrition.to_csv(path_or_buf="P03/fr_bdd_sous_nutrition.csv", sep=';') # crée fichier CSV avec Datafram

p3_bdd_sous_nutrition

<ipython-input-20-620535dc47f5>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p3_sousnutri_2013["nb_personnes"] = pd.to_numeric(p3_sousnutri_2013["Valeur"], errors='coerce')*1000000
<ipython-input-20-620535dc47f5>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p3_sousnutri_2013["Année"] = 2013

      Code zone                                    Zone  nb_personnes  Année
0             2                             Afghanistan     7900000.0   2013
5           202                          Afrique du Sud     2600000.0   2013
10            3                                 Albanie      200000.0   2013
15            4                                 Algérie     1700000.0   2013
20           79                               Allemagne        -999.0   2013
...         ...                                     ...           ...    ...
995         236  Venezuela (République bolivarienne du)     1900000.0   2013
1000        237                                Viet Nam    10400000.0   2013
1005        249                                   Yémen     7200000.0   2013
1010        251                                  Zambie     7000000.0   2013
1015        181                                Zimbabwe     6600000.0   2013

[204 rows x 4 columns]

In [27]:
#  ratio disponibilité alimentaire/habitant en termes de protéines (en kg) par habitant, 
dalim_pop_5142_clean_p["ratio_p"] = dalim_pop_5142_clean_p["Valeur_Dalim"]*365/1000
ratio_p_pdt = dalim_pop_5142_clean_p.pivot_table('ratio_p', index='Zone', columns='Produit')
ratio_p_total = ratio_p_pdt.sum(axis = 1).sort_values(ascending = False).head(20)

ratio_p_total

Zone
Islande                     47.78215
Chine - RAS de Hong-Kong    47.08865
Israël                      46.71270
Lituanie                    45.32205
Maldives                    43.49340
Finlande                    42.85465
Luxembourg                  40.84350
Pays-Bas                    40.67925
Albanie                     40.56610
Portugal                    40.46390
Monténégro                  40.40915
Norvège                     40.38360
France                      40.33250
Irlande                     40.05875
États-Unis d'Amérique       39.93830
Malte                       39.79595
Danemark                    39.66455
Grèce                       39.64995
Italie                      39.59885
Turquie                     39.46380
dtype: float64

In [24]:
p3_veg_ani_Dalimint


p3_veg_ani_Dalimint_otheruse = pd.merge(p3_veg_ani_clean[p3_veg_ani_clean["Code Élément"] == 5154], #rajoute valeur autres_utilisations
                         p3_veg_ani_Dalimint,  how = 'outer',              
             left_on=[ "Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"],
             right_on=["Code zone", "Zone", "Année", "Code Produit", "Produit", "origin"])




# p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse_clean = (p3_veg_ani_Dalimint_sem_perte_nour_alima_otheruse.rename(columns={"Valeur": "autres_utilisations "})).drop(columns=["Code Élément", "Élément", "Unité"])

p3_veg_ani_Dalimint_otheruse["ratio"] = p3_veg_ani_Dalimint_otheruse["Valeur"]  / p3_veg_ani_Dalimint_otheruse["Dalimint"] 

dint_otheruse_ratio = p3_veg_ani_Dalimint_otheruse.pivot_table('ratio', index={"Produit"}, columns= "Année")

dint_otheruse_ratio_tri = dint_otheruse_ratio.sort_values(by=[2013], ascending = False).head(30)
dint_otheruse_ratio_tri

Année                         2013
Produit
Alcool, non Comestible    0.982456
Plantes Aquatiques        0.920661
Huile de Palmistes        0.773645
Piments                   0.739130
Huile de Palme            0.652520
Huile de Colza&Moutarde   0.616865
Palmistes                 0.575625
Huile de Coco             0.570894
Huil Plantes Oleif Autr   0.547179
Huile de Son de Riz       0.502955
Huile de Sésame           0.493671
Sucre non centrifugé      0.465116
Girofles                  0.446809
Huiles de Poissons        0.402734
Crème                     0.356952
Graines de tournesol      0.345253
Graines de coton          0.341593
Manioc                    0.320163
Graisses Animales Crue    0.315107
Épices, Autres            0.298979
Poivre                    0.294118
Sésame                    0.287971
Huile de Tournesol        0.280386
Huile Graines de Coton    0.276206
Huile de Soja             0.272138
Boissons Alcooliques      0.259443
Boissons Fermentés        0.245525
Vin                       0.238618
Feve de Cacao             0.238272
Huiles de Foie de Poisso  0.222222

In [48]:

x = pd.merge(data_veg_ani_DAint_clean,
                         veg_ani_Other_clean,              
             left_on=["Code Produit", "Produit", "Code zone", "Zone"],
             right_on=["Code Produit", "Produit", "Code zone", "Zone"], how = 'right')

x.drop(columns = ["Code Domaine", "Domaine", "Code Élément", "Élément", "Code année", "Description du Symbole", "Symbole", "Importation", 2013]).head(20)

,Code zone,Zone,Code Produit,Produit,Valeur,Other_use,Année,Unité
0,2,Afghanistan,2577,Huile de Palme,119.0,55.0,2013,Milliers de tonnes
1,202,Afrique du Sud,2514,Maïs,10480.0,0.0,2013,Milliers de tonnes
2,202,Afrique du Sud,2532,Manioc,57.0,57.0,2013,Milliers de tonnes
3,202,Afrique du Sud,2577,Huile de Palme,449.0,399.0,2013,Milliers de tonnes
4,3,Albanie,2511,Blé,650.0,130.0,2013,Milliers de tonnes
5,3,Albanie,2805,Riz (Eq Blanchi),25.0,0.0,2013,Milliers de tonnes
6,3,Albanie,2513,Orge,19.0,1.0,2013,Milliers de tonnes
7,3,Albanie,2514,Maïs,420.0,3.0,2013,Milliers de tonnes
8,3,Albanie,2532,Manioc,0.0,0.0,2013,Milliers de tonnes
9,3,Albanie,2542,Sucre Eq Brut,69.0,13.0,2013,Milliers de tonnes
10,3,Albanie,2577,Huile de Palme,2.0,2.0,2013,Milliers de tonnes
11,4,Algérie,2511,Blé,9461.0,820.0,2013,Milliers de tonnes
12,4,Algérie,2542,Sucre Eq Brut,1279.0,190.0,2013,Milliers de tonnes
13,4,Algérie,2577,Huile de Palme,82.0,52.0,2013,Milliers de tonnes
14,79,Allemagne,2511,Blé,16491.0,774.0,2013,Milliers de tonnes
15,79,Allemagne,2805,Riz (Eq Blanchi),290.0,0.0,2013,Milliers de tonnes
16,79,Allemagne,2514,Maïs,7961.0,11.0,2013,Milliers de tonnes
17,79,Allemagne,2532,Manioc,27.0,26.0,2013,Milliers de tonnes
18,79,Allemagne,2542,Sucre Eq Brut,3393.0,440.0,2013,Milliers de tonnes
19,79,Allemagne,2577,Huile de Palme,1612.0,1399.0,2013,Milliers de tonnes

Année                                 2013
Produit             Code Produit
Huile de Palme      2577          0.651857
Manioc              2532          0.320163
Sucre Eq Brut       2542          0.142068
Soja                2555          0.113758
Orge                2513          0.099025
Pommes              2617          0.091661
Riz (Eq Blanchi)    2805          0.064420
Maïs                2514          0.063837
Blé                 2511          0.063393
Tomates             2601          0.048099
Lait - Excl Beurre  2848          0.045745
Fruits, Autres      2625          0.040122
Légumes, Autres     2605          0.034183
Poissons Pelagiques 2763          0.032785
Bananes             2615          0.027843

In [63]:


data_veg_ani_perte = data_veg_ani[(data_veg_ani["Code Élément"] == 664)] # kcal

data_veg_ani_perte_blé = data_veg_ani_perte[(data_veg_ani_perte["Code Produit"] == 2511)]

np.sum(data_veg_ani_perte_blé["Valeur"])

96678.0

In [89]:
x = dalim_pop[dalim_pop["Code Élément"] == 664] # (kcal)
x2 = x[x["Code Produit"] == 2511] #blé
np.sum(x2['la disponibilité alimentaire']) #unité en milliard de cal

1345279.11519

In [90]:
1345279.11519*1000000000/(2500*365)

1474278482.4